# Generated by Django 5.0.1 on 2025-11-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor')], default='ADMIN', max_length=10, verbose_name='Rol'),
        ),
    ]
